--- #YAML:1.0
name:                GPS-Babel
version:             0.10
abstract:            Perl interface to gpsbabel
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    File::Which:                   0
    Geo::Gpx:                      0.15
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
